name: CI

on:
  push:
    tags-ignore:
      - v1.[0-9]+.[0-9]+
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.3.0'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn run test:ci
  e2e:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run e2e
        run: yarn run e2e:ci
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: --dev --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
